require("dotenv").config();
const { Clinic, Service, Doctor } = require("../models");
const { sequelize } = require("../config/database");

const seedClinics = async () => {
  try {
    console.log("🌱 Seeding clinics data...");

    // Create clinics
    const clinics = await Clinic.bulkCreate([
      {
        name: "Klinik PHC Jakarta Pusat",
        address: "Jl. Sudirman No. 123, Jakarta Pusat",
        city: "Jakarta",
        phone: "+62-21-1234567",
        email: "jakarta@phc.com",
        rating: 4.8,
        total_reviews: 1250,
        latitude: -6.2088,
        longitude: 106.8456,
        description: "Klinik utama PHC di Jakarta Pusat dengan layanan lengkap",
        is_active: true,
      },
      {
        name: "Klinik PHC Bandung",
        address: "Jl. Asia Afrika No. 45, Bandung",
        city: "Bandung",
        phone: "+62-22-2345678",
        email: "bandung@phc.com",
        rating: 4.6,
        total_reviews: 890,
        latitude: -6.9175,
        longitude: 107.6191,
        description:
          "Klinik PHC di Bandung dengan fokus layanan kesehatan keluarga",
        is_active: true,
      },
      {
        name: "Klinik PHC Surabaya",
        address: "Jl. Tunjungan No. 67, Surabaya",
        city: "Surabaya",
        phone: "+62-31-3456789",
        email: "surabaya@phc.com",
        rating: 4.7,
        total_reviews: 1100,
        latitude: -7.2575,
        longitude: 112.7521,
        description: "Klinik PHC di Surabaya dengan teknologi medis terbaru",
        is_active: true,
      },
      {
        name: "Klinik PHC Medan",
        address: "Jl. Sudirman No. 89, Medan",
        city: "Medan",
        phone: "+62-61-4567890",
        email: "medan@phc.com",
        rating: 4.5,
        total_reviews: 750,
        latitude: 3.5952,
        longitude: 98.6722,
        description: "Klinik PHC di Medan dengan layanan kesehatan terpadu",
        is_active: true,
      },
    ]);

    console.log("✅ Clinics created successfully");

    // Create services for each clinic
    const services = await Service.bulkCreate([
      // Jakarta Pusat services
      {
        clinic_id: 1,
        name: "Pemeriksaan Umum",
        description: "Pemeriksaan kesehatan umum oleh dokter",
        duration: 30,
        price: 150000,
        icon: "stethoscope",
        color: "#E22345",
        category: "general",
        is_active: true,
      },
      {
        clinic_id: 1,
        name: "Pemeriksaan Gigi",
        description: "Pemeriksaan dan perawatan gigi",
        duration: 45,
        price: 200000,
        icon: "tooth",
        color: "#3B82F6",
        category: "dental",
        is_active: true,
      },
      {
        clinic_id: 1,
        name: "Pemeriksaan Mata",
        description: "Pemeriksaan kesehatan mata",
        duration: 40,
        price: 180000,
        icon: "eye",
        color: "#10B981",
        category: "eye",
        is_active: true,
      },
      {
        clinic_id: 1,
        name: "Pemeriksaan Jantung",
        description: "Pemeriksaan kesehatan jantung",
        duration: 60,
        price: 300000,
        icon: "heart-pulse",
        color: "#EF4444",
        category: "cardiology",
        is_active: true,
      },
      // Bandung services
      {
        clinic_id: 2,
        name: "Pemeriksaan Umum",
        description: "Pemeriksaan kesehatan umum oleh dokter",
        duration: 30,
        price: 140000,
        icon: "stethoscope",
        color: "#E22345",
        category: "general",
        is_active: true,
      },
      {
        clinic_id: 2,
        name: "Pemeriksaan Gigi",
        description: "Pemeriksaan dan perawatan gigi",
        duration: 45,
        price: 190000,
        icon: "tooth",
        color: "#3B82F6",
        category: "dental",
        is_active: true,
      },
      // Surabaya services
      {
        clinic_id: 3,
        name: "Pemeriksaan Umum",
        description: "Pemeriksaan kesehatan umum oleh dokter",
        duration: 30,
        price: 145000,
        icon: "stethoscope",
        color: "#E22345",
        category: "general",
        is_active: true,
      },
      {
        clinic_id: 3,
        name: "Pemeriksaan Gigi",
        description: "Pemeriksaan dan perawatan gigi",
        duration: 45,
        price: 195000,
        icon: "tooth",
        color: "#3B82F6",
        category: "dental",
        is_active: true,
      },
      {
        clinic_id: 3,
        name: "Pemeriksaan Mata",
        description: "Pemeriksaan kesehatan mata",
        duration: 40,
        price: 175000,
        icon: "eye",
        color: "#10B981",
        category: "eye",
        is_active: true,
      },
      // Medan services
      {
        clinic_id: 4,
        name: "Pemeriksaan Umum",
        description: "Pemeriksaan kesehatan umum oleh dokter",
        duration: 30,
        price: 135000,
        icon: "stethoscope",
        color: "#E22345",
        category: "general",
        is_active: true,
      },
    ]);

    console.log("✅ Services created successfully");

    // Create doctors
    const doctors = await Doctor.bulkCreate([
      // Jakarta Pusat doctors
      {
        clinic_id: 1,
        service_id: 1,
        name: "Dr. Sarah Johnson",
        specialization: "Dokter Umum",
        license_number: "SIP.001.2020",
        email: "sarah.johnson@phc.com",
        phone: "+62-812-1234567",
        rating: 4.8,
        total_reviews: 320,
        experience_years: 8,
        bio: "Dokter umum dengan pengalaman 8 tahun di bidang kesehatan keluarga",
        is_active: true,
      },
      {
        clinic_id: 1,
        service_id: 1,
        name: "Dr. Ahmad Rahman",
        specialization: "Dokter Umum",
        license_number: "SIP.002.2020",
        email: "ahmad.rahman@phc.com",
        phone: "+62-812-2345678",
        rating: 4.6,
        total_reviews: 280,
        experience_years: 6,
        bio: "Dokter umum dengan fokus pada kesehatan preventif",
        is_active: true,
      },
      {
        clinic_id: 1,
        service_id: 2,
        name: "Dr. Budi Santoso",
        specialization: "Dokter Gigi",
        license_number: "SIP.003.2020",
        email: "budi.santoso@phc.com",
        phone: "+62-812-3456789",
        rating: 4.9,
        total_reviews: 450,
        experience_years: 12,
        bio: "Dokter gigi dengan spesialisasi ortodonti dan estetika",
        is_active: true,
      },
      {
        clinic_id: 1,
        service_id: 3,
        name: "Dr. Robert Chen",
        specialization: "Dokter Mata",
        license_number: "SIP.004.2020",
        email: "robert.chen@phc.com",
        phone: "+62-812-4567890",
        rating: 4.8,
        total_reviews: 380,
        experience_years: 10,
        bio: "Dokter mata dengan pengalaman di berbagai rumah sakit terkemuka",
        is_active: true,
      },
      {
        clinic_id: 1,
        service_id: 4,
        name: "Dr. Lisa Wong",
        specialization: "Kardiolog",
        license_number: "SIP.005.2020",
        email: "lisa.wong@phc.com",
        phone: "+62-812-5678901",
        rating: 4.9,
        total_reviews: 520,
        experience_years: 15,
        bio: "Kardiolog dengan spesialisasi penyakit jantung koroner",
        is_active: true,
      },
      // Bandung doctors
      {
        clinic_id: 2,
        service_id: 5,
        name: "Dr. Rina Kartika",
        specialization: "Dokter Umum",
        license_number: "SIP.006.2020",
        email: "rina.kartika@phc.com",
        phone: "+62-812-6789012",
        rating: 4.7,
        total_reviews: 290,
        experience_years: 7,
        bio: "Dokter umum dengan pengalaman di klinik keluarga",
        is_active: true,
      },
      {
        clinic_id: 2,
        service_id: 6,
        name: "Dr. Hendra Wijaya",
        specialization: "Dokter Gigi",
        license_number: "SIP.007.2020",
        email: "hendra.wijaya@phc.com",
        phone: "+62-812-7890123",
        rating: 4.5,
        total_reviews: 220,
        experience_years: 5,
        bio: "Dokter gigi dengan fokus pada perawatan gigi anak",
        is_active: true,
      },
      // Surabaya doctors
      {
        clinic_id: 3,
        service_id: 7,
        name: "Dr. Maria Garcia",
        specialization: "Dokter Umum",
        license_number: "SIP.008.2020",
        email: "maria.garcia@phc.com",
        phone: "+62-812-8901234",
        rating: 4.7,
        total_reviews: 310,
        experience_years: 9,
        bio: "Dokter umum dengan pengalaman di bidang kesehatan kerja",
        is_active: true,
      },
      {
        clinic_id: 3,
        service_id: 8,
        name: "Dr. David Kim",
        specialization: "Dokter Gigi",
        license_number: "SIP.009.2020",
        email: "david.kim@phc.com",
        phone: "+62-812-9012345",
        rating: 4.6,
        total_reviews: 260,
        experience_years: 8,
        bio: "Dokter gigi dengan spesialisasi bedah mulut",
        is_active: true,
      },
      {
        clinic_id: 3,
        service_id: 9,
        name: "Dr. Siti Aminah",
        specialization: "Dokter Mata",
        license_number: "SIP.010.2020",
        email: "siti.aminah@phc.com",
        phone: "+62-812-0123456",
        rating: 4.8,
        total_reviews: 340,
        experience_years: 11,
        bio: "Dokter mata dengan pengalaman di berbagai klinik mata",
        is_active: true,
      },
      // Medan doctors
      {
        clinic_id: 4,
        service_id: 10,
        name: "Dr. Joko Widodo",
        specialization: "Dokter Umum",
        license_number: "SIP.011.2020",
        email: "joko.widodo@phc.com",
        phone: "+62-812-1234568",
        rating: 4.5,
        total_reviews: 180,
        experience_years: 6,
        bio: "Dokter umum dengan pengalaman di klinik kesehatan",
        is_active: true,
      },
    ]);

    console.log("✅ Doctors created successfully");
    console.log("🎉 All clinic data seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding clinic data:", error);
  } finally {
    await sequelize.close();
  }
};

// Run the seed function
seedClinics();
